services:
  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend-server:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - backend-server
    ports:
      - "80:5000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: subgate
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: