export {default as DeleteAccount} from "./delete-account.vue"
export {default as GenerateApikey} from "./generate-apikey/generate-apikey.vue"
export {default as UpdateEmail} from "./update-email.vue"
export {default as UpdatePassword} from "./update-password.vue"
export {default as ApikeyCard} from "./apikey-card.vue"
export {default as LoginForm} from "./login-form.vue"